<a href="https://colab.research.google.com/github/Ravravan/DL/blob/main/backpropagation_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa','profile_score','lpa'])

In [3]:
df

   cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [4]:
def initialize_parameters(layer_dims):

  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1, L):

    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))


  return parameters

In [5]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [6]:
#output of given neural
def linear_forward(A_prev, W, b):
  z =np.dot(W.T, A_prev) + b
  return z

In [7]:
# Forward Prop
def L_layer_forward(X, parameters):

  A = X
  L = len(parameters) // 2                  # number of layers in the neural network

  for l in range(1, L+1):
    A_prev = A
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    print("A"+str(l-1)+": ", A_prev)
    print("W"+str(l)+": ", Wl)
    print("b"+str(l)+": ", bl)
    print("--"*20)

    A = linear_forward(A_prev, Wl, bl)
    print("A"+str(l)+": ", A)
    print("**"*20)

  return A,A_prev

In [8]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1)
y = df[['lpa']].values[0][0]
parameters=initialize_parameters([2,2,1])
y_hat,A1 =L_layer_forward(X, parameters)

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************

In [9]:
#loss
(y- 0.32)**2

np.float64(13.5424)

In [10]:
y_hat =y_hat[0][0]

In [11]:
A1

array([[1.6],
       [1.6]])

In [12]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1)
y = df[['lpa']].values[1][0]
y_hat,A1 =L_layer_forward(X, parameters)

A0:  [[7]
 [9]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************

In [13]:
X = df[['cgpa', 'profile_score']].values[2].reshape(2,1)
y = df[['lpa']].values[2][0]
y_hat,A1 =L_layer_forward(X, parameters)

A0:  [[ 6]
 [10]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************

In [14]:
X = df[['cgpa', 'profile_score']].values[3].reshape(2,1)
y = df[['lpa']].values[3][0]
y_hat,A1 =L_layer_forward(X, parameters)

A0:  [[ 5]
 [12]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.7]
 [1.7]]
****************************************
A1:  [[1.7]
 [1.7]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.34]]
****************************************

In [15]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [16]:
update_parameters(parameters,y,y_hat,A1,X)

/tmp/ipykernel_1530/332058445.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
/tmp/ipykernel_1530/332058445.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
/tmp/ipykernel_1530/332058445.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))
/tmp/ipykernel_1530/332058445.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
/tmp/ipykernel_1530/332058445.py:7: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
/tmp/ipykernel_1530/332058445.py:8: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])
/tmp/ipykernel_1530/332058445.py:10: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
/tmp/ipykernel_1530/332058445.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
/tmp/ipykernel_1530/332058445.py:12: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [17]:
parameters

{'W1': array([[0.10816809, 0.11960342],
        [0.10816809, 0.11960342]]),
 'b1': array([[0.00163362],
        [0.00163362]]),
 'W2': array([[0.122644],
        [0.122644]]),
 'b2': array([[0.135964]])}

In [18]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['lpa']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************
A0:  [[7]
 [9]]
W1:  [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1:  [[0.00082267]
 [0.00082267]]
----------------------------------------
A1:  [[1.70612461]
 [1.70612461]]
****************************************
A1:  [[1.70612461]
 [1.70612461]]
W2:  [[0.111776]
 [0.111776]]
b2:  [[0.119136]]
----------------------------------------
A2:  [[0.50054357]]
****************************************
A0:  [[ 6]
 [10]]
W1:  [[0.11458955 0.1168776 ]
 [0.11458955 0.1168776 ]]
b1:  [[0.0019667]
 [0.0019667]]
----------------------------------------
A1:  [[1.83539945]
 [1.87200826]]
****************************************
A1:  [[1.83539945]
 [1.87200826]]
W2:  [[0.12712927]
 [0.12712927]]
b2:  [[0.13612818]]
----------------------------------------
A2:  [[0.6074482]]
****************************************
A0:  [[ 5]
 [12]]
W1:  [[0.12409711 0.13272353]
 [0.12412266 0.13276611]]
b1:  [[0.00355129]
 [0.00355555]]
----------------------------------------
A1:  [[2.11350869]
 [2.26036654]]
****************************************
A1:  [[2.11350869]
 [2.26036654]]
W2:  [[0.14692424]
 [0.14731907]]
b2:  [[0.15810417]]
----------------------------------------
A2:  [[0.80162493]]
****************************************
Epoch -  1 Loss -  25.321744156025517
A0:  [[8]
 [8]]
W1:  [[0.13482804 0.15847776]
 [0.1349909  0.15884991]]
b1:  [[0.00569748]
 [0.0057292 ]]
----------------------------------------
A1:  [[2.16424899]
 [2.54435052]]
****************************************
A1:  [[2.16424899]
 [2.54435052]]
W2:  [[0.17312488]
 [0.17534027]]
b2:  [[0.18773702]]
----------------------------------------
A2:  [[1.00854947]]
****************************************
A0:  [[7]
 [9]]
W1:  [[0.1437341  0.16738383]
 [0.14411185 0.16797086]]
b1:  [[0.00681073]
 [0.00686932]]
----------------------------------------
A1:  [[2.30995614]
 [2.69029382]]
****************************************
A1:  [[2.30995614]
 [2.69029382]]
W2:  [[0.18607337]
 [0.19056287]]
b2:  [[0.19654577]]
----------------------------------------
A2:  [[1.13903718]]
****************************************
A0:  [[ 6]
 [10]]
W1:  [[0.15475619 0.18155508]
 [0.15553536 0.18265822]]
b1:  [[0.00838532]
 [0.00850125]]
----------------------------------------
A1:  [[2.49227603]
 [2.92441391]]
****************************************
A1:  [[2.49227603]
 [2.92441391]]
W2:  [[0.20391068]
 [0.21133712]]
b2:  [[0.21905904]]
----------------------------------------
A2:  [[1.34529793]]
****************************************
A0:  [[ 5]
 [12]]
W1:  [[0.16744187 0.20269788]
 [0.16886056 0.20486689]]
b1:  [[0.0104996 ]
 [0.01072211]]
----------------------------------------
A1:  [[2.87403566]
 [3.48261418]]
****************************************
A1:  [[2.87403566]
 [3.48261418]]
W2:  [[0.22711228]
 [0.23856167]]
b2:  [[0.24787107]]
----------------------------------------
A2:  [[1.73141811]]
****************************************
Epoch -  2 Loss -  18.320004165722047
A0:  [[8]
 [8]]
W1:  [[0.18100301 0.23524462]
 [0.18336278 0.23967222]]
b1:  [[0.01321183]
 [0.01362256]]
----------------------------------------
A1:  [[2.92813816]
 [3.8129573 ]]
****************************************
A1:  [[2.92813816]
 [3.8129573 ]]
W2:  [[0.25739647]
 [0.27525854]]
b2:  [[0.28579571]]
----------------------------------------
A2:  [[2.08903719]]
****************************************
A0:  [[7]
 [9]]
W1:  [[0.18921518 0.24345679]
 [0.1922245  0.24853394]]
b1:  [[0.01423835]
 [0.01473027]]
----------------------------------------
A1:  [[3.06876509]
 [3.95573325]]
****************************************
A1:  [[3.06876509]
 [3.95573325]]
W2:  [[0.26858759]
 [0.28983138]]
b2:  [[0.29365331]]
----------------------------------------
A2:  [[2.26438116]]
****************************************
A0:  [[ 6]
 [10]]
W1:  [[0.20014476 0.25750911]
 [0.20415354 0.26387128]]
b1:  [[0.01579972]
 [0.01643442]]
----------------------------------------
A1:  [[3.25820367]
 [4.20020184]]
****************************************
A1:  [[3.25820367]
 [4.20020184]]
W2:  [[0.28537753]
 [0.31147414]]
b2:  [[0.31694538]]
----------------------------------------
A2:  [[2.55501776]]
****************************************
A0:  [[ 5]
 [12]]
W1:  [[0.21287024 0.27871824]
 [0.21822616 0.28732564]]
b1:  [[0.01792063]
 [0.01877986]]
----------------------------------------
A1:  [[3.7009857 ]
 [4.86027872]]
****************************************
A1:  [[3.7009857 ]
 [4.86027872]]
W2:  [[0.30782644]
 [0.34041338]]
b2:  [[0.34730334]]
----------------------------------------
A2:  [[3.14106851]]
****************************************
Epoch -  3 Loss -  9.473661050729628
A0:  [[8]
 [8]]
W1:  [[0.22585131 0.3098728 ]
 [0.23281    0.32232686]]
b1:  [[0.02051684]
 [0.02169662]]
----------------------------------------
A1:  [[3.68980727]
 [5.07929387]]
****************************************
A1:  [[3.68980727]
 [5.07929387]]
W2:  [[0.33639014]
 [0.37792434]]
b2:  [[0.38564221]]
----------------------------------------
A2:  [[3.54644581]]
****************************************
A0:  [[7]
 [9]]
W1:  [[0.22831673 0.31233823]
 [0.23558598 0.32510284]]
b1:  [[0.02082502]
 [0.02204362]]
----------------------------------------
A1:  [[3.73931597]
 [5.13433676]]
****************************************
A1:  [[3.73931597]
 [5.13433676]]
W2:  [[0.3397372 ]
 [0.38253181]]
b2:  [[0.38343892]]
----------------------------------------
A2:  [[3.61787081]]
****************************************
A0:  [[ 6]
 [10]]
W1:  [[0.23509059 0.32104747]
 [0.24326252 0.33497268]]
b1:  [[0.02179271]
 [0.02314027]]
----------------------------------------
A1:  [[3.86496148]
 [5.2991519 ]]
****************************************
A1:  [[3.86496148]
 [5.2991519 ]]
W2:  [[0.35007363]
 [0.39672445]]
b2:  [[0.39948871]]
----------------------------------------
A2:  [[3.85481293]]
****************************************
A0:  [[ 5]
 [12]]
W1:  [[0.24452913 0.33677838]
 [0.25406036 0.35296907]]
b1:  [[0.02336581]
 [0.02493991]]
----------------------------------------
A1:  [[4.29473577]
 [5.94446068]]
****************************************
A1:  [[4.29473577]
 [5.94446068]]
W2:  [[0.36665576]
 [0.41945979]]
b2:  [[0.42375017]]
----------------------------------------
A2:  [[4.49190204]]
****************************************
Epoch -  4 Loss -  3.2520938634031613
A0:  [[8]
 [8]]
W1:  [[0.25426555 0.36014576]
 [0.2653287  0.38001309]]
b1:  [[0.02531309]
 [0.02719358]]
----------------------------------------
A1:  [[4.18206705]
 [5.94846444]]
****************************************
A1:  [[4.18206705]
 [5.94846444]]
W2:  [[0.388199  ]
 [0.44927837]]
b2:  [[0.45429457]]
----------------------------------------
A2:  [[4.75028523]]
****************************************
A0:  [[7]
 [9]]
W1:  [[0.24968072 0.35556094]
 [0.26004246 0.37472686]]
b1:  [[0.02473998]
 [0.0265328 ]]
----------------------------------------
A1:  [[4.11288719]
 [5.88800108]]
****************************************
A1:  [[4.11288719]
 [5.88800108]]
W2:  [[0.38192351]
 [0.44035228]]
b2:  [[0.43885171]]
----------------------------------------
A2:  [[4.60245475]]
****************************************
A0:  [[ 6]
 [10]]
W1:  [[0.25182457 0.35831731]
 [0.26251936 0.37791144]]
b1:  [[0.02504625]
 [0.02688664]]
----------------------------------------
A1:  [[4.16118723]
 [5.95590488]]
****************************************
A1:  [[4.16118723]
 [5.95590488]]
W2:  [[0.38519363]
 [0.44503378]]
b2:  [[0.44582887]]
----------------------------------------
A2:  [[4.69927052]]
****************************************
A0:  [[ 5]
 [12]]
W1:  [[0.25800593 0.36861958]
 [0.26970762 0.38989188]]
b1:  [[0.02607647]
 [0.02808469]]
----------------------------------------
A1:  [[4.55259758]
 [6.54988512]]
****************************************
A1:  [[4.55259758]
 [6.54988512]]
W2:  [[0.39601879]
 [0.46052782]]
b2:  [[0.46312928]]
----------------------------------------
A2:  [[5.28244776]]
****************************************
Epoch -  5 Loss -  1.3407132589299962

{'W1': array([[0.26507636, 0.38558861],
        [0.27800387, 0.40980287]]),
 'b1': array([[0.02749056],
        [0.02974394]]),
 'W2': array([[0.41165744],
        [0.48302736]]),
 'b2': array([[0.48646246]])}

#using keras

In [19]:
import numpy as np
import pandas as pd

In [22]:
df1 = pd.DataFrame([[8,8,9],[10,11,12],[5,8,9]], columns =['cgpa','profile_score','lpa'])

In [23]:
df1

   cgpa  profile_score  lpa
0     8              8    9
1    10             11   12
2     5              8    9

In [34]:
import tensorflow
from  tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [25]:
model = Sequential()

model.add(Dense(2,activation='linear', input_dim=2))
model.add(Dense(1,activation='linear'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [26]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [27]:
model.get_weights()

[array([[ 0.43067312,  0.2480545 ],
        [-0.21172154,  0.94299304]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.4079528],
        [-1.3824153]], dtype=float32),
 array([0.], dtype=float32)]

In [28]:
new_weights = [np.array([[0.1,0.1],[0.1,0.1]], dtype=np.float32),
               np.array([0.,0.], dtype=np.float32),
               np.array([[0.1],[0.1]],dtype=np.float32),
               np.array([0.], dtype=np.float32)]

In [30]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [35]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

# Move set_weights after compile
model.set_weights(new_weights)

In [37]:
model.fit(df1.iloc[:,0:-1].values, df1.iloc[:,-1].values, epochs=100, verbose=1, batch_size=1)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 31.4496
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 30.6122
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 29.6572
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 28.7778
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 28.0170
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 27.0249
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 26.2877
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25.3281
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 24.5664
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 23.7971
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 22.9834
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 22.1421
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 21.4218
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 20.6590
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 19.9142
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 19.1037
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 18.4976
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 17.7643
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 17.1295
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 16.4595
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 15.7404
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 15.1310
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 14.5663
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 13.9454
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 13.3714
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 12.8467
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 12.3109
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 11.7969
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 11.2202
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 10.7398
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 10.2962
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 9.8412
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 9.3855
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 8.9099
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 8.5271
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 8.1073
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 7.7393
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7.3797
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7.0162
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 6.6686
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 6.3034
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 6.0168
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 5.7223
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 5.4024
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 5.1469
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 4.8810
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 4.6140
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.3687
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 4.1442
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 3.9477
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 3.7240
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.5332
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.3462
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.1736
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.9908
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.8351
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.7036
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.5391
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.4146
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.2957
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.1645
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2.0593
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.9521
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.8342
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.7583
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.6704
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.5706
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.4985
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.4278
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.3586
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.2994
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.2477
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.1843
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.1340
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.0862
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.0486
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.9956
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.9583
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.9360
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.8914
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.8668
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.8364
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.8093
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.7878
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.7570
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.7343
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.7165
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.7027
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6863
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6774
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6561
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6493
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6311
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.6193
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6093
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6009
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.5937
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.5861
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.5792
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.5779

In [38]:
model.get_weights()

[array([[0.50561535, 0.50561535],
        [0.5225627 , 0.5225627 ]], dtype=float32),
 array([0.43939957, 0.43939957], dtype=float32),
 array([[0.5192612],
        [0.5192612]], dtype=float32),
 array([0.30507782], dtype=float32)]